name: subneptune
channels:
  - conda-forge
  - bokeh
dependencies:
  - numba=0.60.0
  - numpy=1.26.4
  - scipy=1.11.4
  - bokeh=3.0.2
  - photochem=0.7.0
  - mpi4py=4.0.1
  - dill=0.3.9
  - tqdm=4.66.5
  - astropy=6.1.4
  - pandas=2.2.3
  - xarray=2024.9.0
  - pymultinest=2.12
  - matplotlib
  - pip=25.2
  - wget=1.25.0
  - tar=1.35
  - unzip=6.0
  - jupyter=1.1.1
  - cmake=3.31.8 
  - ninja=1.13.1 
  - cython=3.1.6
  - fypp=3.2
  - c-compiler=1.11.0 
  - cxx-compiler=1.11.0
  - fortran-compiler=1.11.0 
  - git=2.51.0
  - scikit-build=0.18.1
  - corner=2.2.3

